# @format

version: "3.0"

services:
  api:
    container_name: "gc-api"
    volumes:
      - ./gc_api:/workspace/gc_api:cached
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    working_dir: /workspace/gc_api
    command: uvicorn main:app --reload --port=8080 --host=0.0.0.0
    ports:
      - 10112:8080
